export const mockData = {
  overview: {
    totalRevenue: 125000,
    totalSales: 2458,
    totalStores: 5,
    lowStockItems: 12,
    totalEmployees: 23,
  },
  stores: [
    {
      id: 1,
      name: 'Verdulería Centro',
      revenue: 35000,
      sales: 680,
      employees: 5,
      status: 'active',
    },
    {
      id: 2,
      name: 'Verdulería Norte',
      revenue: 28000,
      sales: 542,
      employees: 4,
      status: 'active',
    },
    {
      id: 3,
      name: 'Verdulería Sur',
      revenue: 22000,
      sales: 435,
      employees: 5,
      status: 'active',
    },
    {
      id: 4,
      name: 'Verdulería Este',
      revenue: 25000,
      sales: 498,
      employees: 4,
      status: 'active',
    },
    {
      id: 5,
      name: 'Verdulería Oeste',
      revenue: 15000,
      sales: 303,
      employees: 5,
      status: 'maintenance',
    },
  ],
  products: [
    {
      id: 1,
      name: 'Tomate',
      category: 'Verduras',
      totalStock: 450,
      price: 2.5,
      lowStock: false,
    },
    {
      id: 2,
      name: 'Lechuga',
      category: 'Verduras',
      totalStock: 230,
      price: 1.8,
      lowStock: false,
    },
    {
      id: 3,
      name: 'Zanahoria',
      category: 'Verduras',
      totalStock: 15,
      price: 2.2,
      lowStock: true,
    },
    {
      id: 4,
      name: 'Manzana',
      category: 'Frutas',
      totalStock: 180,
      price: 3.5,
      lowStock: false,
    },
    {
      id: 5,
      name: 'Banana',
      category: 'Frutas',
      totalStock: 25,
      price: 2.8,
      lowStock: true,
    },
    {
      id: 6,
      name: 'Palta',
      category: 'Frutas',
      totalStock: 90,
      price: 4.2,
      lowStock: false,
    },
    {
      id: 7,
      name: 'Cebolla',
      category: 'Verduras',
      totalStock: 5,
      price: 1.9,
      lowStock: true,
    },
    {
      id: 8,
      name: 'Papa',
      category: 'Verduras',
      totalStock: 320,
      price: 1.5,
      lowStock: false,
    },
  ],
  stockByStore: [
    {
      storeName: 'Centro',
      tomate: 120,
      lechuga: 80,
      zanahoria: 5,
      manzana: 45,
      banana: 10,
      palta: 20,
      cebolla: 2,
      papa: 95,
    },
    {
      storeName: 'Norte',
      tomate: 95,
      lechuga: 60,
      zanahoria: 3,
      manzana: 35,
      banana: 8,
      palta: 15,
      cebolla: 1,
      papa: 80,
    },
    {
      storeName: 'Sur',
      tomate: 85,
      lechuga: 45,
      zanahoria: 4,
      manzana: 40,
      banana: 4,
      palta: 25,
      cebolla: 1,
      papa: 70,
    },
    {
      storeName: 'Este',
      tomate: 90,
      lechuga: 35,
      zanahoria: 3,
      manzana: 35,
      banana: 3,
      palta: 18,
      cebolla: 1,
      papa: 50,
    },
    {
      storeName: 'Oeste',
      tomate: 60,
      lechuga: 10,
      zanahoria: 0,
      manzana: 25,
      banana: 0,
      palta: 12,
      cebolla: 0,
      papa: 25,
    },
  ],
  employees: [
    {
      id: 1,
      name: 'Magnus Mefisto',
      store: 'Centro',
      position: 'Gerente',
      sales: 45000,
      status: 'active',
    },
    {
      id: 2,
      name: 'Nico Algoenel Pelo',
      store: 'Norte',
      position: 'Cajero',
      sales: 28000,
      status: 'active',
    },
    {
      id: 3,
      name: 'Luis Allier',
      store: 'Sur',
      position: 'Cajero',
      sales: 22000,
      status: 'active',
    },
    {
      id: 4,
      name: 'Apu Nahasapeemapetilon',
      store: 'Este',
      position: 'Cajero',
      sales: 25000,
      status: 'active',
    },
    {
      id: 5,
      name: 'Laura Lamamadelmono',
      store: 'Oeste',
      position: 'Cajero',
      sales: 15000,
      status: 'sick_leave',
    },
  ],
}
